[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.42"
nannou = "0.19.0"
sysinfo = { version = "0.37.2", features = ["default"] }

aphrodite = { path = "../../crates/aphrodite" }
logos = { path = "../../crates/logos" }
kamea = { path = "../../crates/kamea" }
