[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.42"
nannou = "0.19.0"
sysinfo = { version = "0.37.2", features = ["default"] }

aphrodite = { path = "../../crates/aphrodite" }
logos = { path = "../../crates/logos" }
kamea = { path = "../../crates/kamea" }
talisman_core = { path = "../../core" }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
async-trait = "0.1"
sha2 = "0.10.8"
